name: Run Program on Push

on:
  push:
    branches:
      - main  # push 到 main 分支時觸發

  schedule:
    - cron: '01 21 * * *'  # 台灣時間 05:01（UTC 20:01）
    - cron: '11 6 * * *'   # 每天下午2點11分觸發

jobs:
  run_program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install uv
        run: |
          pipx install uv      

      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt

      - name: Run your program
        env:
          GROQ_API_KEY: ${{secrets.GROQ_API_KEY}}
          FifeBase: ${{secrets.FireBase}}
    
        run: |
          uv run python RAG_Test.py > result.txt 
          # ↑ 把程式輸出存到 result.txt (包含錯誤)

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rag-output
          path: result.txt
