name: Run Program on Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *' 
jobs:
  run_program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set Google credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_B64 }}" | base64 -d > $GITHUB_WORKSPACE/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/gcp-key.json" >> $GITHUB_ENV

      - name: Run Program and save output
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          today=$(date +'%Y%m%d')
          python RAG_Test.py > result_${today}.txt
          cat result_${today}.txt
          echo "TODAY=$today" >> $GITHUB_ENV   # 存到環境變數，後面可以用

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rag-result-${{ env.TODAY }}
          path: result_*.txt
