name: Run Program on Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '01 21 * * *'
    - cron: '11 6 * * *'

jobs:
  run_program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set Google credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_B64 }}" | base64 --decode > $GITHUB_WORKSPACE/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/gcp-key.json" >> $GITHUB_ENV


      - name: Run Program and save output
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python RAG_Test.py > result.txt
          cat result.txt
